---

scm_version: 6.3.1
cluster_version_cm: 6.3.1
scm_port: 7180
scm_default_user: admin
scm_default_pass: admin

scm_repositories:
  - https://archive.cloudera.com/cdh6/6.3.2/parcels/

scm_products:
  - product: CDH
    version: 6.3.2-1.cdh6.3.2.p0.1605554
