---

- include_vars: ../../../group_vars/cdh_servers.yml
- include_vars: ../../../group_vars/scm_server.yml
- include_vars: ../../../group_vars/db_server.yml

# change ownership of data directory
- name: Change ownership of Data directory
  file:
    path: /dfs/data0
    state: directory
    owner: hdfs
    group: hdfs
    recurse: yes
